spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bwtable-mysql?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 1
  jpa:
    hibernate:
      defer-datasource-initialization: true
      ddl-auto: update
    show-sql: true
#  sql:  // data.sql 을 위한 설정
#    init:
#      mode: always
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-default} # HS512 알고리즘을 사용할 경우, 비밀 키는 최소 512비트(64바이트) 이상
    accessTokenValidityInMilliseconds: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}
    refreshTokenValidityInMilliseconds: ${JWT_REFRESH_TOKEN_VALIDITY:86400000}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/api/oauth2/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
---
spring:
  config:
    activate:
      on-profile: prod
#jwt:
#  secret: ${JWT_SECRET}
#  accessTokenValidityInMilliseconds: ${JWT_ACCESS_TOKEN_VALIDITY}
#  refreshTokenValidityInMilliseconds: ${JWT_REFRESH_TOKEN_VALIDITY}