spring:
  activate:
    on-profile: prod
  multipart:
    max-file-size: 5MB
    max-request-size: 10MB
  iamport:
    api:
      key: ${IMP_API_KEY}
      secret: ${IMP_API_SECRET}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:${EC2_IP}//${:3306/bwtable-mysql?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 1
  jpa:
    hibernate:
      defer-datasource-initialization: true
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-default} # HS512 알고리즘을 사용할 경우, 비밀 키는 최소 512비트(64바이트) 이상
    accessTokenValidityInMilliseconds: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}
    refreshTokenValidityInMilliseconds: ${JWT_REFRESH_TOKEN_VALIDITY:86400000}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://${EC2_IP}:8080/api/oauth2/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
