-- -- 회원 데이터
-- INSERT INTO member (login_type, email, password, name, nickname, phone, role,
--                     business_number, profile_image_url, provider, provider_id)
-- VALUES ('EMAIL', 'john.doe@example.com', 'password123', '홍길동', '홍길이',
--         '01011112222', 'GUEST', NULL, NULL, NULL, NULL),
--        ('EMAIL', 'jane.smith@example.com', 'password123', '김영희', '영희',
--         '01033334444', 'GUEST', NULL, NULL, NULL, NULL),
--        ('SOCIAL', 'kakao_user@example.com', 'password123', '카카오 사용자',
--         '카카오유저', '01055556666', 'GUEST', NULL, NULL, 'Kakao', 'kakao123'),
--        ('SOCIAL', 'google_user@example.com', 'password123', '구글 사용자',
--         '구글유저', '01077778888', 'GUEST', NULL, NULL, 'Google',
--         'google123'),
--        ('EMAIL', 'owner@example.com', 'ownerpassword123', '사장님 이름',
--         '사장님닉네임', '01099990000', 'OWNER', '1234567890', NULL, NULL,
--         NULL);
--
-- INSERT INTO restaurant (name, description, address, latitude, longitude, contact, closed_day, notice, link, category_id, average_rating, member_id)
-- VALUES ('트렌디 카페',
--         '편안한 분위기의 카페로 다양한 음료와 디저트를 제공합니다.',
--         '서울특별시 강남구 역삼동 123-45',
--         37.4979, -- 위도
--         127.0276, -- 경도
--         '0212345678',
--         '일요일',
--         '매주 일요일은 정기휴무입니다.',
--         'http://example.com/trendy-cafe',
--         1, -- 카테고리 ID (예: 1번 카테고리)
--         4.5, -- 평균 평점
--         31); -- 회원 ID울특별시 서초구 양재동 1213', 0245678931, NULL);